# Generated by Django 3.0.5 on 2020-04-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='main_photo',
            field=models.ImageField(blank=True, upload_to='photo/%Y/%m/%d/'),
        ),
    ]
